In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('C:\Codding\Data Science\PROJECT\Data_ML_project.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\POOJA\AppData\Local\Temp\ipykernel_24176\2984551966.py:1: SyntaxWarning: invalid escape sequence '\C'
  df=pd.read_csv('C:\Codding\Data Science\PROJECT\Data_ML_project.csv')


In [4]:
df

Course Name  \
0                Acing the Product Management Interview   
1                  The Business of Product Management I   
2               The Art & Science of Product Management   
3     Machine Learning Algorithms: Supervised Learni...   
4                             Data for Machine Learning   
...                                                 ...   
3448                      Understanding Korean Politics   
3449  International Marketing & Cross Industry Growt...   
3450  Gender, Family, and Social Change in Contempor...   
3451                         Deep Learning for Business   
3452                   Re-imaging God in Korean Context   

                                  University Aptitude Score Family_Income  \
0                 Advancing Women in Product             71          High   
1                 Advancing Women in Product             75           Low   
2                 Advancing Women in Product             62        Medium   
3     Alberta Machine Intelligence Institute             73           Low   
4     Alberta Machine Intelligence Institute             76           Low   
...                                      ...            ...           ...   
3448                       Yonsei University             63          High   
3449                       Yonsei University             63           Low   
3450                       Yonsei University             94        Medium   
3451                       Yonsei University             79        Medium   
3452                       Yonsei University             87        Medium   

     Parental_Education_Level Previous Score Extracurricular activity  \
0                 High School             69                      Yes   
1                     College             65                      Yes   
2                 High School             63                       No   
3                     College             66                       No   
4                Postgraduate             65                       No   
...                       ...            ...                      ...   
3448                  College             72                      Yes   
3449                  College             64                       No   
3450              High School             70                      Yes   
3451                  College             69                      Yes   
3452             Postgraduate             68                      Yes   

     Difficulty Level Course rating  
0            Advanced             5  
1            Advanced           4.8  
2            Beginner             5  
3        Intermediate           4.7  
4            Beginner           4.4  
...               ...           ...  
3448     Intermediate           4.8  
3449         Beginner           4.6  
3450     Intermediate           4.7  
3451         Beginner           4.3  
3452     Intermediate           4.7  

[3453 rows x 9 columns]

In [5]:
df['Parental_Education_Level'].value_counts()

Parental_Education_Level
High School                 1721
College                     1053
Postgraduate                 672
High school                    1
Parental_Education_Level       1
Name: count, dtype: int64

In [6]:
print(df['Parental_Education_Level'])

0        High School
1            College
2        High School
3            College
4       Postgraduate
            ...     
3448         College
3449         College
3450     High School
3451         College
3452    Postgraduate
Name: Parental_Education_Level, Length: 3453, dtype: object


In [7]:
df['Parental_Education_Level'] = df['Parental_Education_Level'].replace('High school', 'High School')

In [8]:
df['Parental_Education_Level'].value_counts()

Parental_Education_Level
High School                 1722
College                     1053
Postgraduate                 672
Parental_Education_Level       1
Name: count, dtype: int64

In [9]:
import random

income_ranges = {
    'Low': (55, 63),
    'Medium': (70, 80),
    'High': (81, 93),
}
education_level = {
    'College': (55, 63),    
    'High School': (70, 80),
    'Postgraduate': (81, 93),
}
difficulty_level = {
    'Beginner':	(57,62),
    'Advanced'	:(88,97),
    'Intermediate':(67,75),
    'Conversant':	(78,85),
    'Not Calibrated':	(50,56)
}

def get_random_from_range(category, ranges): # Added ranges as an argument
    if category in ranges:
        Low, High = ranges[category]
        return random.randint(Low, High)
    return None

df['Education_Num'] = df['Parental_Education_Level'].apply(lambda x: get_random_from_range(x, education_level)) 
df['Income_Level_Num'] = df['Family_Income'].apply(lambda x: get_random_from_range(x, income_ranges))
df['Difficulty_level_Num'] = df['Difficulty Level'].apply(lambda x: get_random_from_range(x, difficulty_level))


In [10]:
df.head()

Course Name  \
0             Acing the Product Management Interview   
1               The Business of Product Management I   
2            The Art & Science of Product Management   
3  Machine Learning Algorithms: Supervised Learni...   
4                          Data for Machine Learning   

                               University Aptitude Score Family_Income  \
0              Advancing Women in Product             71          High   
1              Advancing Women in Product             75           Low   
2              Advancing Women in Product             62        Medium   
3  Alberta Machine Intelligence Institute             73           Low   
4  Alberta Machine Intelligence Institute             76           Low   

  Parental_Education_Level Previous Score Extracurricular activity  \
0              High School             69                      Yes   
1                  College             65                      Yes   
2              High School             63                       No   
3                  College             66                       No   
4             Postgraduate             65                       No   

  Difficulty Level Course rating  Education_Num  Income_Level_Num  \
0         Advanced             5           71.0              87.0   
1         Advanced           4.8           57.0              58.0   
2         Beginner             5           76.0              71.0   
3     Intermediate           4.7           59.0              59.0   
4         Beginner           4.4           87.0              57.0   

   Difficulty_level_Num  
0                  97.0  
1                  92.0  
2                  58.0  
3                  75.0  
4                  57.0

In [11]:
df.columns

Index(['Course Name', 'University', 'Aptitude Score', 'Family_Income',
       'Parental_Education_Level', 'Previous Score',
       'Extracurricular activity', 'Difficulty Level', 'Course rating',
       'Education_Num', 'Income_Level_Num', 'Difficulty_level_Num'],
      dtype='object')

In [12]:
df=df.drop(columns=[ 'Family_Income',
       'Parental_Education_Level','Difficulty Level'])

In [13]:
df.head()

Course Name  \
0             Acing the Product Management Interview   
1               The Business of Product Management I   
2            The Art & Science of Product Management   
3  Machine Learning Algorithms: Supervised Learni...   
4                          Data for Machine Learning   

                               University Aptitude Score Previous Score  \
0              Advancing Women in Product             71             69   
1              Advancing Women in Product             75             65   
2              Advancing Women in Product             62             63   
3  Alberta Machine Intelligence Institute             73             66   
4  Alberta Machine Intelligence Institute             76             65   

  Extracurricular activity Course rating  Education_Num  Income_Level_Num  \
0                      Yes             5           71.0              87.0   
1                      Yes           4.8           57.0              58.0   
2                       No             5           76.0              71.0   
3                       No           4.7           59.0              59.0   
4                       No           4.4           87.0              57.0   

   Difficulty_level_Num  
0                  97.0  
1                  92.0  
2                  58.0  
3                  75.0  
4                  57.0

In [14]:
df.isna().sum()

Course Name                 0
University                  0
Aptitude Score              0
Previous Score              0
Extracurricular activity    0
Course rating               0
Education_Num               6
Income_Level_Num            1
Difficulty_level_Num        1
dtype: int64

In [15]:
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

In [16]:
df.isna().sum()

Course Name                 0
University                  0
Aptitude Score              0
Previous Score              0
Extracurricular activity    0
Course rating               0
Education_Num               0
Income_Level_Num            0
Difficulty_level_Num        0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3453 entries, 0 to 3452
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Course Name               3453 non-null   object 
 1   University                3453 non-null   object 
 2   Aptitude Score            3453 non-null   object 
 3   Previous Score            3453 non-null   object 
 4   Extracurricular activity  3453 non-null   object 
 5   Course rating             3453 non-null   object 
 6   Education_Num             3453 non-null   float64
 7   Income_Level_Num          3453 non-null   float64
 8   Difficulty_level_Num      3453 non-null   float64
dtypes: float64(3), object(6)
memory usage: 242.9+ KB


In [18]:
df['Course rating'].unique()

array(['5', '4.8', '4.7', '4.4', '4.5', '4.9', '4', '4.6', '4.3', '3.7',
       'Not Calibrated', '4.2', '4.1', '3.6', '2.9', '3.5', '3.1', '3.9',
       '3.2', '3.8', '3', '3.4', '2.6', '1.9', '2.4', '2.8', '2.5', '3.3',
       '2', '1', '2.3', 'Course Rating'], dtype=object)

In [19]:
df['Course rating'] = df['Course rating'].replace('Not Calibrated', 4.5)

In [20]:
df['Course rating'] = df['Course rating'].replace('Course Rating', 4.5)

In [21]:
df['Course rating'].unique()

array(['5', '4.8', '4.7', '4.4', '4.5', '4.9', '4', '4.6', '4.3', '3.7',
       4.5, '4.2', '4.1', '3.6', '2.9', '3.5', '3.1', '3.9', '3.2', '3.8',
       '3', '3.4', '2.6', '1.9', '2.4', '2.8', '2.5', '3.3', '2', '1',
       '2.3'], dtype=object)

In [22]:
df['Previous Score'].unique()

array(['69', '65', '63', '66', '67', '61', '60', '64', '68', '72', '74',
       '62', '71', '75', '70', '73', '82', '86', '99', '76', '79', '59',
       '84', '58', '77', '88', '80', '78', '57', '94', '101', '87', '96',
       '97', '89', '91', '55', '92', '100', 'Apptitude', '83'],
      dtype=object)

In [23]:
df['Previous Score'] = df['Previous Score'].replace('Apptitude', 64)

In [24]:
df['Previous Score'].unique()

array(['69', '65', '63', '66', '67', '61', '60', '64', '68', '72', '74',
       '62', '71', '75', '70', '73', '82', '86', '99', '76', '79', '59',
       '84', '58', '77', '88', '80', '78', '57', '94', '101', '87', '96',
       '97', '89', '91', '55', '92', '100', 64, '83'], dtype=object)

In [25]:
df['Aptitude Score'].unique()

array(['71', '75', '62', '73', '76', '81', '54', '68', '87', '95', '60',
       '56', '53', '52', '89', '72', '57', '59', '74', '90', '66', '82',
       '85', '83', '93', '78', '96', '80', '79', '94', '86', '63', '88',
       '99', '64', '77', '92', '97', '84', '91', '58', '70', '65', '67',
       '61', '50', '69', '51', '98', '55', '100', 'Previous_Scores'],
      dtype=object)

In [26]:
df['Aptitude Score']=df['Aptitude Score'].replace('Previous_Scores',80)

In [27]:
columns_to_convert = ['Aptitude Score', 'Previous Score','Course rating']
df[columns_to_convert] = df[columns_to_convert].astype(float)


In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3453 entries, 0 to 3452
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Course Name               3453 non-null   object 
 1   University                3453 non-null   object 
 2   Aptitude Score            3453 non-null   float64
 3   Previous Score            3453 non-null   float64
 4   Extracurricular activity  3453 non-null   object 
 5   Course rating             3453 non-null   float64
 6   Education_Num             3453 non-null   float64
 7   Income_Level_Num          3453 non-null   float64
 8   Difficulty_level_Num      3453 non-null   float64
dtypes: float64(6), object(3)
memory usage: 242.9+ KB


In [29]:
df.to_csv('Cleaned_ML_Dataset.csv')

In [30]:
data=pd.read_csv('C:\Codding\Data Science\PROJECT\Cleaned_ML_Dataset.csv')

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\POOJA\AppData\Local\Temp\ipykernel_24176\2723885497.py:1: SyntaxWarning: invalid escape sequence '\C'
  data=pd.read_csv('C:\Codding\Data Science\PROJECT\Cleaned_ML_Dataset.csv')


In [31]:
data.head()

Unnamed: 0                                        Course Name  \
0           0             Acing the Product Management Interview   
1           1               The Business of Product Management I   
2           2            The Art & Science of Product Management   
3           3  Machine Learning Algorithms: Supervised Learni...   
4           4                          Data for Machine Learning   

                               University  Aptitude Score  Previous Score  \
0              Advancing Women in Product            71.0            69.0   
1              Advancing Women in Product            75.0            65.0   
2              Advancing Women in Product            62.0            63.0   
3  Alberta Machine Intelligence Institute            73.0            66.0   
4  Alberta Machine Intelligence Institute            76.0            65.0   

  Extracurricular activity  Course rating  Education_Num  Income_Level_Num  \
0                      Yes            5.0           71.0              87.0   
1                      Yes            4.8           57.0              58.0   
2                       No            5.0           76.0              71.0   
3                       No            4.7           59.0              59.0   
4                       No            4.4           87.0              57.0   

   Difficulty_level_Num  
0                  97.0  
1                  92.0  
2                  58.0  
3                  75.0  
4                  57.0

In [32]:
data=data.drop(columns='Unnamed: 0')

In [33]:
data.head()

Course Name  \
0             Acing the Product Management Interview   
1               The Business of Product Management I   
2            The Art & Science of Product Management   
3  Machine Learning Algorithms: Supervised Learni...   
4                          Data for Machine Learning   

                               University  Aptitude Score  Previous Score  \
0              Advancing Women in Product            71.0            69.0   
1              Advancing Women in Product            75.0            65.0   
2              Advancing Women in Product            62.0            63.0   
3  Alberta Machine Intelligence Institute            73.0            66.0   
4  Alberta Machine Intelligence Institute            76.0            65.0   

  Extracurricular activity  Course rating  Education_Num  Income_Level_Num  \
0                      Yes            5.0           71.0              87.0   
1                      Yes            4.8           57.0              58.0   
2                       No            5.0           76.0              71.0   
3                       No            4.7           59.0              59.0   
4                       No            4.4           87.0              57.0   

   Difficulty_level_Num  
0                  97.0  
1                  92.0  
2                  58.0  
3                  75.0  
4                  57.0

In [34]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [35]:
# Convert categorical features into numerical values
le_course = LabelEncoder()
le_university = LabelEncoder()
le_extracurricular = LabelEncoder()

In [36]:
data['Course Name'] = le_course.fit_transform(data['Course Name'])
data['University'] = le_university.fit_transform(data['University'])
data['Extracurricular activity'] = le_extracurricular.fit_transform(data['Extracurricular activity'])

In [37]:
# Normalize or standardize numerical features if needed
scaler = StandardScaler()
data[['Aptitude Score', 'Previous Score', 'Course rating', 'Education_Num', 'Income_Level_Num', 'Difficulty_level_Num']] = scaler.fit_transform(
    data[['Aptitude Score', 'Previous Score', 'Course rating', 'Education_Num', 'Income_Level_Num', 'Difficulty_level_Num']]
)

In [38]:
# Check the transformed data
print(data.head())

   Course Name  University  Aptitude Score  Previous Score  \
0           80           0       -0.286094        0.427031   
1         3031           0       -0.008423       -0.588316   
2         3017           0       -0.910852       -1.095989   
3         2070           1       -0.147259       -0.334479   
4          936           1        0.060994       -0.588316   

   Extracurricular activity  Course rating  Education_Num  Income_Level_Num  \
0                         2       1.335872      -0.134090          1.476587   
1                         2       0.737006      -1.464182         -1.148771   
2                         1       1.335872       0.340943          0.028113   
3                         1       0.437573      -1.274169         -1.058242   
4                         1      -0.460726       1.386016         -1.239301   

   Difficulty_level_Num  
0              1.724765  
1              1.370071  
2             -1.041846  
3              0.164113  
4             -1.11278

In [39]:
from sklearn.decomposition import TruncatedSVD

# Selecting the numerical features for SVD
X = data[['Aptitude Score', 'Previous Score', 'Course rating', 'Education_Num', 'Income_Level_Num', 'Difficulty_level_Num']]

In [40]:
# Apply SVD (n_components is the number of latent factors we want to extract)
svd = TruncatedSVD(n_components=3)  # Adjust this based on your data
X_svd = svd.fit_transform(X)

# Show the reduced dimensionality matrix
print(X_svd)

[[ 0.40665263  0.39156651  1.15173232]
 [-1.00895631  0.2661219  -1.55013143]
 [-0.37672422 -2.12468896  0.18255063]
 ...
 [ 1.45142884  0.21110518 -0.30114684]
 [ 0.43471975  0.01389473  0.46715831]
 [ 1.18024194 -0.01669721  0.63136702]]


In [41]:
import numpy as np

# Reconstruct the matrix from the SVD components
X_reconstructed = svd.inverse_transform(X_svd)

# For example, if you want to predict the course rating for a specific student, compare the components
student_index = 0  # Change this index to select different students
predicted_course_rating = X_reconstructed[student_index, 2]  # This would give you the predicted rating for the third course feature
print(f"Predicted Course Rating for Student {student_index}: {predicted_course_rating}")


Predicted Course Rating for Student 0: -0.2810914807742236


In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import mean_squared_error

In [43]:
# Step 1: Load the data
data = df

In [44]:
data.head()

Course Name  \
0             Acing the Product Management Interview   
1               The Business of Product Management I   
2            The Art & Science of Product Management   
3  Machine Learning Algorithms: Supervised Learni...   
4                          Data for Machine Learning   

                               University  Aptitude Score  Previous Score  \
0              Advancing Women in Product            71.0            69.0   
1              Advancing Women in Product            75.0            65.0   
2              Advancing Women in Product            62.0            63.0   
3  Alberta Machine Intelligence Institute            73.0            66.0   
4  Alberta Machine Intelligence Institute            76.0            65.0   

  Extracurricular activity  Course rating  Education_Num  Income_Level_Num  \
0                      Yes            5.0           71.0              87.0   
1                      Yes            4.8           57.0              58.0   
2                       No            5.0           76.0              71.0   
3                       No            4.7           59.0              59.0   
4                       No            4.4           87.0              57.0   

   Difficulty_level_Num  
0                  97.0  
1                  92.0  
2                  58.0  
3                  75.0  
4                  57.0

In [45]:
# Step 2: Preprocessing
# Convert numeric columns to appropriate types
for col in ['Aptitude Score', 'Income_Level_Num', 'Previous Score', 'Course rating']:
    data[col] = pd.to_numeric(data[col], errors='coerce')

In [46]:
# Handle missing data
data['Education_Num'] = data['Education_Num'].fillna('Unknown')


In [47]:
# Encode categorical variables
label_encoders = {}
for col in ['Course Name', 'University']:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

In [48]:
# Step 3: Feature Matrix and Target
# Features: All except 'Course rating'
# Target: 'Course rating'
X = data.drop(columns=['Course Name'])
y = data['Course Name']

In [49]:
# Normalize numerical features
scaler = StandardScaler()
X[['Aptitude Score', 'Income_Level_Num', 'Previous Score']] = scaler.fit_transform(
    X[['Aptitude Score', 'Income_Level_Num', 'Previous Score']]
)


In [50]:
# Step 4: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [51]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import TruncatedSVD


In [52]:
# Step 1: Identify and encode categorical columns
categorical_cols = ['Extracurricular activity']  # Add other non-numeric columns if needed
label_encoders = {}


In [53]:
for col in categorical_cols:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    label_encoders[col] = le  # Save encoder for later use

In [54]:
# Step 2: Handle missing values
X_train = X_train.fillna(0)  # Replace NaN with 0 (or use mean/median as appropriate)

In [55]:
X_train = X_train.fillna(X_train.mean())

In [56]:
# Step 3: Scale numeric features
scaler = StandardScaler()


In [57]:

X_train_scaled = scaler.fit_transform(X_train)

In [58]:
# Step 4: Apply Truncated SVD
svd = TruncatedSVD(n_components=10, random_state=42)