#To print the Statement

In [1]:
print("Hello")

Hello


In [2]:
import numpy as np

In [6]:
v = np.array([1,-1,2])
w = np.array([5,6,9])

In [7]:
print (v+w)

[ 6  5 11]


In [8]:
print(v-w)

[-4 -7 -7]


In [9]:
print(3*v)

[ 3 -3  6]


In [10]:
print(np.linalg.norm(v))

2.449489742783178


In [12]:
s=np.dot(v,w)