# Numpy - Array Manipulation

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[8, 3, 4, 6],
       [3, 9, 3, 3],
       [1, 8, 1, 9]], dtype=int32)

In [4]:
arr.reshape(6,2)

array([[8, 3],
       [4, 6],
       [3, 9],
       [3, 3],
       [1, 8],
       [1, 9]], dtype=int32)

In [5]:
arr.reshape(2,6)

array([[8, 3, 4, 6, 3, 9],
       [3, 3, 1, 8, 1, 9]], dtype=int32)

In [6]:
arr.T

array([[8, 3, 1],
       [3, 9, 8],
       [4, 3, 1],
       [6, 3, 9]], dtype=int32)

In [7]:
arr.flatten()

array([8, 3, 4, 6, 3, 9, 3, 3, 1, 8, 1, 9], dtype=int32)

In [8]:
arr1 = np.array([1,2,3,4])

In [9]:
arr1

array([1, 2, 3, 4])

In [10]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [12]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [13]:
arr

array([[8, 3, 4, 6],
       [3, 9, 3, 3],
       [1, 8, 1, 9]], dtype=int32)

In [14]:
np.squeeze(arr)

array([[8, 3, 4, 6],
       [3, 9, 3, 3],
       [1, 8, 1, 9]], dtype=int32)

In [17]:
data = np.array([[1],[2],[3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 4])

In [22]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [23]:
arr1

array([1, 2, 3, 4])

In [24]:
np.roll(arr1, 2)                #shift the data

array([3, 4, 1, 2])

In [25]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Numpy - Binary Operators

In [26]:
arr1 = np.random.randint(1,10,(3,4))

In [27]:
arr2 = np.random.randint(1,10,(3,4))

In [28]:
arr1

array([[5, 6, 9, 3],
       [8, 8, 5, 4],
       [5, 2, 3, 4]], dtype=int32)

In [29]:
arr2

array([[1, 6, 1, 6],
       [1, 5, 3, 5],
       [6, 7, 5, 1]], dtype=int32)

In [30]:
arr1 +arr2

array([[ 6, 12, 10,  9],
       [ 9, 13,  8,  9],
       [11,  9,  8,  5]], dtype=int32)

In [31]:
arr1*arr2

array([[ 5, 36,  9, 18],
       [ 8, 40, 15, 20],
       [30, 14, 15,  4]], dtype=int32)

In [32]:
arr1/arr2

array([[5.        , 1.        , 9.        , 0.5       ],
       [8.        , 1.6       , 1.66666667, 0.8       ],
       [0.83333333, 0.28571429, 0.6       , 4.        ]])

In [33]:
arr1-arr2

array([[ 4,  0,  8, -3],
       [ 7,  3,  2, -1],
       [-1, -5, -2,  3]], dtype=int32)

In [34]:
arr1%arr2

array([[0, 0, 0, 3],
       [0, 3, 2, 4],
       [5, 2, 3, 0]], dtype=int32)

In [35]:
arr1 ** arr2

array([[    5, 46656,     9,   729],
       [    8, 32768,   125,  1024],
       [15625,   128,   243,     4]], dtype=int32)

In [36]:
arr1

array([[5, 6, 9, 3],
       [8, 8, 5, 4],
       [5, 2, 3, 4]], dtype=int32)

In [37]:
arr2

array([[1, 6, 1, 6],
       [1, 5, 3, 5],
       [6, 7, 5, 1]], dtype=int32)

In [38]:
arr1 & arr2

array([[1, 6, 1, 2],
       [0, 0, 1, 4],
       [4, 2, 1, 0]], dtype=int32)

In [39]:
~arr1

array([[ -6,  -7, -10,  -4],
       [ -9,  -9,  -6,  -5],
       [ -6,  -3,  -4,  -5]], dtype=int32)

In [40]:
arr1 | arr2

array([[ 5,  6,  9,  7],
       [ 9, 13,  7,  5],
       [ 7,  7,  7,  5]], dtype=int32)

In [41]:
arr1 > arr2

array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [False, False, False,  True]])

# Numpy - String Funtion

In [42]:
arr = np.array(['pooja','verma'])

In [43]:
arr

array(['pooja', 'verma'], dtype='<U5')

In [44]:
np.char.upper(arr)

array(['POOJA', 'VERMA'], dtype='<U5')

In [45]:
np.char.title(arr)

array(['Pooja', 'Verma'], dtype='<U5')

In [46]:
np.char.capitalize(arr)

array(['Pooja', 'Verma'], dtype='<U5')

# Numpy - mathematical Function

In [47]:
arr1

array([[5, 6, 9, 3],
       [8, 8, 5, 4],
       [5, 2, 3, 4]], dtype=int32)

In [48]:
np.sin(arr1)

array([[-0.95892427, -0.2794155 ,  0.41211849,  0.14112001],
       [ 0.98935825,  0.98935825, -0.95892427, -0.7568025 ],
       [-0.95892427,  0.90929743,  0.14112001, -0.7568025 ]])

In [49]:
np.cos(arr1)

array([[ 0.28366219,  0.96017029, -0.91113026, -0.9899925 ],
       [-0.14550003, -0.14550003,  0.28366219, -0.65364362],
       [ 0.28366219, -0.41614684, -0.9899925 , -0.65364362]])

In [50]:
np.tan(arr1)

array([[-3.38051501, -0.29100619, -0.45231566, -0.14254654],
       [-6.79971146, -6.79971146, -3.38051501,  1.15782128],
       [-3.38051501, -2.18503986, -0.14254654,  1.15782128]])

In [51]:
np.tanh(arr1)

array([[0.9999092 , 0.99998771, 0.99999997, 0.99505475],
       [0.99999977, 0.99999977, 0.9999092 , 0.9993293 ],
       [0.9999092 , 0.96402758, 0.99505475, 0.9993293 ]])

In [52]:
np.log10(arr1)

array([[0.69897   , 0.77815125, 0.95424251, 0.47712125],
       [0.90308999, 0.90308999, 0.69897   , 0.60205999],
       [0.69897   , 0.30103   , 0.47712125, 0.60205999]])

In [53]:
np.exp(arr1)

array([[1.48413159e+02, 4.03428793e+02, 8.10308393e+03, 2.00855369e+01],
       [2.98095799e+03, 2.98095799e+03, 1.48413159e+02, 5.45981500e+01],
       [1.48413159e+02, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01]])

In [54]:
np.sqrt(arr1)

array([[2.23606798, 2.44948974, 3.        , 1.73205081],
       [2.82842712, 2.82842712, 2.23606798, 2.        ],
       [2.23606798, 1.41421356, 1.73205081, 2.        ]])

In [55]:
np.power(arr1,2)

array([[25, 36, 81,  9],
       [64, 64, 25, 16],
       [25,  4,  9, 16]], dtype=int32)

In [56]:
np.mean(arr1)

np.float64(5.166666666666667)

In [57]:
np.median(arr1)

np.float64(5.0)

In [58]:
np.std(arr1)

np.float64(2.1147629234082532)

In [59]:
np.var(arr1)

np.float64(4.472222222222222)

In [60]:
np.min(arr1)

np.int32(2)

In [61]:
np.max(arr1)

np.int32(9)

In [62]:
import numpy as np

In [63]:
np.argsort(np.array(['p','a']))

array([1, 0])