In [2]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a = [2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b = np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c = a               #sowlo copy

In [16]:
c

array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c[0] = 100

In [19]:
c

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
d = np.copy(a)            #deep copy

In [22]:
d

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [24]:
a[1] = 400

In [25]:
a

array([100, 400,   3,   4])

In [26]:
d

array([100,   2,   3,   4])

In [27]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [31]:
np.fromstring('243 256',sep = ' ')

array([243., 256.])

In [32]:
np.fromstring('4,5',sep = ',')

array([4., 5.])

# Numpy -Data Types

In [33]:
l = [1,2,3,4,5,6]

In [34]:
ar = np.array(l)

In [38]:
ar

array([1, 2, 3, 4, 5, 6])

In [35]:
ar.ndim

1

In [36]:
ar2 = np.array([[1,2,3],[4,5,6]])

In [37]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
ar2.ndim

2

In [39]:
ar.size

6

In [40]:
ar2.size

6

In [41]:
ar.shape

(6,)

In [42]:
ar2.shape

(2, 3)

In [43]:
ar.dtype

dtype('int64')

In [44]:
ar2.dtype

dtype('int64')

In [45]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [46]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [47]:
ar22.dtype

dtype('float64')

In [48]:
list(range(5))

[0, 1, 2, 3, 4]

In [49]:
list(range(0.5,5))

TypeError: 'float' object cannot be interpreted as an integer

In [50]:
list(np.arange(2.3,5.6,0.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
ar4 = np.zeros((3,4,2,3))

In [56]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [57]:
np.ones(4)

array([1., 1., 1., 1.])

In [58]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
on = np.ones((2,3,2))

In [60]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [61]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [62]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [63]:
np.eye(5)            #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [65]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [66]:
arr = np.random.randn(2,3)         #  mean=0 , std = 1

In [67]:
import pandas as pd

In [68]:
pd.DataFrame(arr)

0         1         2
0 -2.359515 -0.585855  1.224068
1 -0.822349 -0.189334 -0.321496

In [69]:
np.random.rand(3,5)

array([[0.14281184, 0.64248106, 0.4463762 , 0.66777251, 0.52788372],
       [0.07833148, 0.00557304, 0.57365805, 0.16810473, 0.22088205],
       [0.07252207, 0.42979839, 0.33005263, 0.7426938 , 0.67243136]])

In [70]:
np.random.randint(1,50,(3,3))       #always produce data

array([[ 9, 43, 43],
       [ 2, 44, 27],
       [10,  7, 17]], dtype=int32)

In [71]:
ary = np.random.randint(1,99,(50,50)) 

In [72]:
pd.DataFrame(ary).to_csv('test.csv')

In [73]:
arr = np.random.rand(3,4)

In [74]:
arr

array([[0.98946641, 0.00605328, 0.01100461, 0.72621567],
       [0.85665161, 0.38030035, 0.06713835, 0.59645888],
       [0.21117314, 0.95246046, 0.74835198, 0.90705755]])

In [75]:
arr1 = arr.reshape(6,2)

In [76]:
arr1

array([[0.98946641, 0.00605328],
       [0.01100461, 0.72621567],
       [0.85665161, 0.38030035],
       [0.06713835, 0.59645888],
       [0.21117314, 0.95246046],
       [0.74835198, 0.90705755]])

In [77]:
arr1[1][1]

np.float64(0.7262156745280586)

In [78]:
arr1[1,1]

np.float64(0.7262156745280586)

In [79]:
arr1[2:5,1]

array([0.38030035, 0.59645888, 0.95246046])

In [80]:
arr = np.random.randint(1,100,(5,5))

In [81]:
arr

array([[ 6, 27, 35, 93, 60],
       [87,  3, 90, 29, 36],
       [93, 93, 60, 98, 44],
       [91, 88, 26, 37, 55],
       [55, 95, 17, 20, 18]], dtype=int32)

In [82]:
arr > 50

array([[False, False, False,  True,  True],
       [ True, False,  True, False, False],
       [ True,  True,  True,  True, False],
       [ True,  True, False, False,  True],
       [ True,  True, False, False, False]])

In [83]:
arr[arr>50]

array([93, 60, 87, 90, 93, 93, 60, 98, 91, 88, 55, 55, 95], dtype=int32)

In [84]:
arr

array([[ 6, 27, 35, 93, 60],
       [87,  3, 90, 29, 36],
       [93, 93, 60, 98, 44],
       [91, 88, 26, 37, 55],
       [55, 95, 17, 20, 18]], dtype=int32)

In [85]:
arr[2:4,[1,2]]

array([[93, 60],
       [88, 26]], dtype=int32)

In [86]:
arr[[2,4],[1,2]]

array([93, 17], dtype=int32)

In [87]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [88]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [89]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 2, 2]], dtype=int32)

In [90]:
arr1 + arr2

array([[3, 3, 3],
       [3, 4, 3],
       [2, 3, 4]], dtype=int32)

In [91]:
arr1 -arr2

array([[-1, -1, -1],
       [ 1,  0,  1],
       [ 0, -1,  0]], dtype=int32)

In [92]:
arr1 /arr2

array([[0.5, 0.5, 0.5],
       [2. , 1. , 2. ],
       [1. , 0.5, 1. ]])

In [93]:
arr1 *arr2

array([[2, 2, 2],
       [2, 4, 2],
       [1, 2, 4]], dtype=int32)

In [94]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [95]:
arr2

array([[2, 2, 2],
       [1, 2, 1],
       [1, 2, 2]], dtype=int32)

In [96]:
arr1 @ arr2

array([[ 4,  6,  5],
       [ 8, 12, 10],
       [ 5,  8,  7]], dtype=int32)

In [97]:
arr1/0

C:\Users\POOJA\AppData\Local\Temp\ipykernel_8624\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [98]:
arr1 + 100

array([[101, 101, 101],
       [102, 102, 102],
       [101, 101, 102]], dtype=int32)

In [99]:
arr1**2

array([[1, 1, 1],
       [4, 4, 4],
       [1, 1, 4]], dtype=int32)

In [100]:
arr = np.zeros((4,4))

In [101]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
row = np.array([1,2,3,3])

In [103]:
arr + row

array([[1., 2., 3., 3.],
       [1., 2., 3., 3.],
       [1., 2., 3., 3.],
       [1., 2., 3., 3.]])

In [104]:
row.T

array([1, 2, 3, 3])

In [105]:
col = np.array([[1,2,3,3]])

In [106]:
col.T

array([[1],
       [2],
       [3],
       [3]])

In [107]:
arr + col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [108]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
arr1 = np.random.randint(1,4,(3,4))

In [110]:
arr1

array([[3, 3, 2, 2],
       [1, 2, 1, 2],
       [3, 3, 2, 3]], dtype=int32)

In [111]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        , 1.41421356],
       [1.73205081, 1.73205081, 1.41421356, 1.73205081]])

In [112]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  7.3890561 ,  7.3890561 ],
       [ 2.71828183,  7.3890561 ,  2.71828183,  7.3890561 ],
       [20.08553692, 20.08553692,  7.3890561 , 20.08553692]])

In [113]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.30103   , 0.30103   ],
       [0.        , 0.30103   , 0.        , 0.30103   ],
       [0.47712125, 0.47712125, 0.30103   , 0.47712125]])