# Sort , Search & Counting Function

In [2]:
import numpy as np

In [3]:
arr = np.array([8,6,9,45,62,625,37,3])

In [10]:
np.sort(arr)

array([  3,   6,   8,   9,  37,  45,  62, 625])

In [11]:
np.searchsorted(arr, 40)

np.int64(3)

In [12]:
arr1 = np.array([0,25,3,78,25,0,0,0,0,0,0])

In [13]:
np.count_nonzero(arr1)

4

In [14]:
arr

array([  8,   6,   9,  45,  62, 625,  37,   3])

In [15]:
np.where(arr > 8)

(array([2, 3, 4, 5, 6]),)

In [16]:
np.extract(arr > 8 ,arr)

array([  9,  45,  62, 625,  37])

In [17]:
arr.byteswap()

array([ 576460752303423488,  432345564227567616,  648518346341351424,
       3242591731706757120, 4467570830351532032, 8143071076239278080,
       2666130979403333632,  216172782113783808])

# Numpy Copy & Views

In [18]:
arr

array([  8,   6,   9,  45,  62, 625,  37,   3])

In [19]:
a = np.copy(arr)

In [20]:
b = arr.view()

In [21]:
b

array([  8,   6,   9,  45,  62, 625,  37,   3])

In [22]:
b[0] = 67

In [23]:
b

array([ 67,   6,   9,  45,  62, 625,  37,   3])

In [24]:
arr

array([ 67,   6,   9,  45,  62, 625,  37,   3])

# Numpy - matrix Library

In [25]:
import numpy.matlib as nm

In [26]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [27]:
nm.ones((3,2))

matrix([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [28]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Numpy - Linear Algebra

In [29]:
arr1 = np.random.randint([[2,3],[4,5]])

In [30]:
arr2 = np.random.randint([[5,3],[2,5]])

In [31]:
arr1

array([[0, 1],
       [0, 4]], dtype=int32)

In [32]:
arr2

array([[0, 0],
       [1, 0]], dtype=int32)

In [33]:
np.dot(arr1,arr2)

array([[1, 0],
       [4, 0]], dtype=int32)

In [34]:
arr1@arr2

array([[1, 0],
       [4, 0]], dtype=int32)